import {Component} from '@angular/core';

@Component({
  template: `
    <section id="Neonursing">
      orem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut sem ut tortor blandit vulputate id vitae tortor. Praesent posuere urna in tincidunt pretium. Nunc malesuada imperdiet justo id ultrices. Integer egestas dignissim dolor, quis placerat felis gravida non. Proin at mauris id enim rutrum feugiat a non dolor. Sed ut laoreet diam. Vestibulum porttitor eu metus at dignissim. Aliquam interdum congue odio ut tincidunt. Aliquam sit amet libero ut magna vehicula imperdiet. Fusce rhoncus facilisis pharetra. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam ultrices urna quam, et dapibus tortor aliquam ut.

      Fusce sed velit nec quam hendrerit dignissim sit amet at risus. Fusce blandit massa sit amet pulvinar dapibus. Nam ullamcorper diam ac tellus fermentum porta. Sed euismod turpis nec tellus sagittis tincidunt. Fusce sagittis risus eget bibendum tristique. Aliquam faucibus convallis molestie. Nam vehicula, quam sit amet elementum molestie, velit urna bibendum sapien, non tempor orci lacus eu massa. Mauris luctus varius aliquet. Nulla cursus consequat ipsum, fringilla consequat augue porta a. Aenean ut porttitor ipsum. Aenean nec urna id libero efficitur hendrerit sed in sapien. Curabitur pretium efficitur erat sed volutpat.

      Aenean quis arcu congue, congue odio sed, lobortis nunc. Cras quis ornare tortor. Suspendisse dictum blandit pulvinar. Pellentesque gravida mauris velit, non tempus sapien convallis at. Sed condimentum ipsum sem, eu vestibulum ex fermentum non. Cras ultrices pretium nulla in malesuada. Fusce dapibus malesuada efficitur. Nulla vitae justo dui. Morbi blandit neque leo. Integer porttitor orci nisl, in sollicitudin ipsum interdum et. In tincidunt dolor at mauris ultrices ultricies. Donec nec posuere mi. In egestas euismod imperdiet.

      Donec tincidunt risus nec erat viverra, vitae faucibus est maximus. Donec scelerisque quam a tortor tincidunt fermentum. Quisque sit amet mauris ante. Aenean in lacinia sem, ac cursus magna. Cras sed dolor magna. Ut felis odio, mattis sed ante at, ultrices pharetra ex. Sed at nisi a felis rhoncus cursus. Proin posuere aliquam quam. Aliquam consequat rhoncus neque non aliquam. Nunc sagittis luctus felis, sed molestie lectus tincidunt sit amet. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam eget risus egestas, mollis risus eu, cursus augue. Fusce sed bibendum felis.

      Suspendisse placerat lorem ac ligula fermentum scelerisque. Donec et posuere sem. Praesent rutrum orci ut libero semper interdum. Proin feugiat, felis eu cursus hendrerit, quam mi vehicula nisl, ac pulvinar sem lacus ut ante. Duis nec ultricies tortor. Ut tristique aliquam velit, sit amet dignissim turpis elementum sodales. Fusce ac quam ullamcorper, ultricies ante et, porttitor mauris. Fusce sed dictum massa, vitae ullamcorper eros. Ut sodales nisl vitae felis imperdiet aliquam. Vestibulum placerat aliquam augue id ultrices. Nunc condimentum, nulla quis rutrum aliquam, velit diam mattis nulla, in bibendum ligula lacus porttitor lacus. Phasellus nec dolor diam. Mauris finibus risus nibh, id maximus metus interdum id. Pellentesque placerat orci quis dignissim gravida.
    </section>
    <div style="height: 650px"></div>
    <section id="interpersonalna-opiekna-nad-kobieta-i-noworodkiem">
      orem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut sem ut tortor blandit vulputate id vitae tortor. Praesent posuere urna in tincidunt pretium. Nunc malesuada imperdiet justo id ultrices. Integer egestas dignissim dolor, quis placerat felis gravida non. Proin at mauris id enim rutrum feugiat a non dolor. Sed ut laoreet diam. Vestibulum porttitor eu metus at dignissim. Aliquam interdum congue odio ut tincidunt. Aliquam sit amet libero ut magna vehicula imperdiet. Fusce rhoncus facilisis pharetra. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam ultrices urna quam, et dapibus tortor aliquam ut.

      Fusce sed velit nec quam hendrerit dignissim sit amet at risus. Fusce blandit massa sit amet pulvinar dapibus. Nam ullamcorper diam ac tellus fermentum porta. Sed euismod turpis nec tellus sagittis tincidunt. Fusce sagittis risus eget bibendum tristique. Aliquam faucibus convallis molestie. Nam vehicula, quam sit amet elementum molestie, velit urna bibendum sapien, non tempor orci lacus eu massa. Mauris luctus varius aliquet. Nulla cursus consequat ipsum, fringilla consequat augue porta a. Aenean ut porttitor ipsum. Aenean nec urna id libero efficitur hendrerit sed in sapien. Curabitur pretium efficitur erat sed volutpat.

      Aenean quis arcu congue, congue odio sed, lobortis nunc. Cras quis ornare tortor. Suspendisse dictum blandit pulvinar. Pellentesque gravida mauris velit, non tempus sapien convallis at. Sed condimentum ipsum sem, eu vestibulum ex fermentum non. Cras ultrices pretium nulla in malesuada. Fusce dapibus malesuada efficitur. Nulla vitae justo dui. Morbi blandit neque leo. Integer porttitor orci nisl, in sollicitudin ipsum interdum et. In tincidunt dolor at mauris ultrices ultricies. Donec nec posuere mi. In egestas euismod imperdiet.

      Donec tincidunt risus nec erat viverra, vitae faucibus est maximus. Donec scelerisque quam a tortor tincidunt fermentum. Quisque sit amet mauris ante. Aenean in lacinia sem, ac cursus magna. Cras sed dolor magna. Ut felis odio, mattis sed ante at, ultrices pharetra ex. Sed at nisi a felis rhoncus cursus. Proin posuere aliquam quam. Aliquam consequat rhoncus neque non aliquam. Nunc sagittis luctus felis, sed molestie lectus tincidunt sit amet. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam eget risus egestas, mollis risus eu, cursus augue. Fusce sed bibendum felis.

      Suspendisse placerat lorem ac ligula fermentum scelerisque. Donec et posuere sem. Praesent rutrum orci ut libero semper interdum. Proin feugiat, felis eu cursus hendrerit, quam mi vehicula nisl, ac pulvinar sem lacus ut ante. Duis nec ultricies tortor. Ut tristique aliquam velit, sit amet dignissim turpis elementum sodales. Fusce ac quam ullamcorper, ultricies ante et, porttitor mauris. Fusce sed dictum massa, vitae ullamcorper eros. Ut sodales nisl vitae felis imperdiet aliquam. Vestibulum placerat aliquam augue id ultrices. Nunc condimentum, nulla quis rutrum aliquam, velit diam mattis nulla, in bibendum ligula lacus porttitor lacus. Phasellus nec dolor diam. Mauris finibus risus nibh, id maximus metus interdum id. Pellentesque placerat orci quis dignissim gravida.
    </section>
  `
})
export class ConferencePage {

}
